# Generated by Django 5.2.16 on 2026-07-14 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable Chatbot')),
                ('welcome_message', models.TextField(default='Hello 👋\n\nWelcome to RIGBUILDER.\n\nI am your AI PC Building Assistant.\n\nI can help you with:\n🖥 Custom PC Builds\n🎮 Gaming Performance\n⚙ Compatibility\n💰 Product Recommendations\n🚚 Shipping\n💳 Payments\n📦 Orders\n🔄 Returns\n\nType your question below.', verbose_name='Welcome Message')),
                ('ai_personality', models.TextField(default='You are the official RIGBUILDER AI Assistant, a premium, friendly, and expert PC sales and support engineer. Help users design their dream gaming PCs, troubleshoot compatibility, check budget targets, and navigate store policies. Always behave like a smart sales assistant. Proactively suggest matching parts, explain technical terms simply (e.g. TDP, RAM Speed, Bottleneck, PCIe gen), and remind them of cancellation rules (e.g. 15% restocking fee for custom rigs cancelled after 24 hours). Keep formatting clean using Markdown lists, bold text, and HTML tables where appropriate.', verbose_name='System Prompt / Personality')),
                ('max_messages_per_session', models.PositiveIntegerField(default=50, verbose_name='Rate Limit (Max messages per session)')),
            ],
            options={
                'verbose_name': 'Chatbot Configuration',
                'verbose_name_plural': 'Chatbot Configuration',
            },
        ),
        migrations.CreateModel(
            name='LocalFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Local FAQ',
                'verbose_name_plural': 'Local FAQs',
            },
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Log',
                'verbose_name_plural': 'Conversation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
