# Generated by Django 5.2.16 on 2026-07-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='system_requirements',
            field=models.TextField(blank=True, help_text='Enter required parts or capabilities (e.g. Multi-GPU, 32GB RAM, 850W PSU)', null=True),
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='target_system',
            field=models.CharField(blank=True, help_text='e.g. Crypto Currency System, Trading System, Deep Learning System', max_length=150, null=True),
        ),
    ]
