# Generated by Django 5.2.16 on 2026-07-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_pcbuild_system_requirements_pcbuild_target_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='custom_required_categories',
            field=models.TextField(blank=True, help_text='Comma-separated category names explicitly checked by the user', null=True),
        ),
    ]
