# Generated by Django 5.2.16 on 2026-07-11 19:39

import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=products.models.OnlineImageField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=products.models.OnlineImageField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=products.models.OnlineImageField(max_length=500),
        ),
    ]
